In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('data/scMNC/efeature_filtered.csv')

In [3]:
import numpy as np
from sklearn import preprocessing

In [5]:
data_folder = "data/scMNC/"
data1 = pd.read_csv(data_folder + "geneExp_filtered.csv")
data2 = pd.read_csv(data_folder + "efeature_filtered.csv")
sample_names1 = data1.columns[1:]
sample_names2 = np.array(data2)[:, 0]
feature_names1 = data1.iloc[:,0]
feature_names2 = data2.columns[3:]
assert (sample_names1 == sample_names2).all()

In [6]:
data1 = np.transpose(np.array(data1)[:, 1:])
data2 = np.array(data2)[:, 3:]

In [7]:
meta = pd.read_csv(data_folder + "20200711_patchseq_metadata_mouse.csv")
meta_names = np.array(meta.columns)
meta_sid = np.argwhere(meta_names == 'transcriptomics_sample_id')[0][0]
meta_ttype = np.argwhere(meta_names == 't_type')[0][0]
meta = np.array(meta)
meta_idx = [np.argwhere(meta[:, meta_sid] == sample_names1[i])[0][0] for i in range(sample_names1.shape[0])]
type1 = type2 = np.array([x.split(' ')[0] for x in meta[meta_idx, meta_ttype]])

In [8]:
labels = [type1, type2]
features = [np.array(feature_names1), np.array(feature_names2)]
feature_dict = {'upstroke_downstroke_ratio_short_square': 'up-downstroke_ratio_short_square', 'upstroke_downstroke_ratio_long_square': 'up-downstroke_ratio_long_square'}

In [24]:
# Preprocessing
data1 = preprocessing.scale(data1, axis=0)
data2 = preprocessing.scale(data2, axis=0)
data1[np.isnan(data1)] = 0  # Replace NaN with average
data2[np.isnan(data2)] = 0
dataset = [data1, data2]

# Replace NULL feature names
for i in range(len(features)):
    if features[i] is None:
        features[i] = np.array([f'Feature {i}' for i in range(dataset[i].shape[1])])

In [26]:
labels

[array(['Sst', 'Sst', 'Sst', ..., 'Pvalb', 'Pvalb', 'Pvalb'], dtype='<U8'),
 array(['Sst', 'Sst', 'Sst', ..., 'Pvalb', 'Pvalb', 'Pvalb'], dtype='<U8')]

In [28]:
features

[array(['Cbln2', 'Enc1', 'Tespa1', ..., 'Dapk1', 'Ppm1k', 'Ankrd36'],
       dtype=object),
 array(['vrest', 'ri', 'sag', 'tau', 'vm_for_sag', 'f_i_curve_slope',
        'adaptation', 'latency', 'avg_isi',
        'upstroke_downstroke_ratio_long_square', 'peak_v_long_square',
        'peak_t_long_square', 'trough_v_long_square',
        'trough_t_long_square', 'fast_trough_v_long_square',
        'fast_trough_t_long_square', 'threshold_v_long_square',
        'threshold_i_long_square', 'threshold_t_long_square',
        'upstroke_downstroke_ratio_ramp', 'peak_v_ramp', 'peak_t_ramp',
        'trough_v_ramp', 'trough_t_ramp', 'fast_trough_v_ramp',
        'fast_trough_t_ramp', 'threshold_v_ramp', 'threshold_i_ramp',
        'threshold_t_ramp', 'upstroke_downstroke_ratio_short_square',
        'peak_v_short_square', 'peak_t_short_square',
        'trough_v_short_square', 'trough_t_short_square',
        'fast_trough_v_short_square', 'fast_trough_t_short_square',
        'threshold_v_short_square', 'threshold_i_short_square',
        'threshold_t_short_square'], dtype=object)]

In [17]:
df2 = pd.read_csv('data/scMNC/geneExp_filtered.csv')
df2.head()

,gene,PS0817_E1-50_S19,PS0817_E1-50_S26,PS0817_E1-50_S27,PS0817_E1-50_S28,PS0817_E1-50_S46,PS0817_E1-50_S52,PS0830_E1-50_S17,PS0830_E1-50_S26,PS0830_E1-50_S70,...,SM-J39TJ_S280_E1-50,SM-J39TJ_S281_E1-50,SM-J39TJ_S285_E1-50,SM-J39TJ_S287_E1-50,SM-J39T2_S314_E1-50,SM-J39S6_S190_E1-50,SM-J3A1L_S592_E1-50,SM-J3A1L_S593_E1-50,SM-J3A1L_S603_E1-50,SM-J3A1L_S604_E1-50
0,Cbln2,0,0,0,0,0,0,0,193,0,...,1,27,0,0,0,0,0,0,0,5
1,Enc1,0,11,0,0,0,0,0,4,0,...,13,25,0,21,17,0,0,0,6,0
2,Tespa1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Lrrtm4,12,0,267,1005,115,31,1174,287,2349,...,54,212,369,284,248,138,544,679,54,16
4,Pdzd2,0,0,31,1,17,1,42,3,1,...,0,19,1,22,0,0,1,10,0,17

In [25]:
df2.set_index("gene", inplace=True)

In [31]:
df_gene = df2.transpose()
df_gene.head()

gene,Cbln2,Enc1,Tespa1,Lrrtm4,Pdzd2,Fam19a1,Hs6st3,Dgkb,Hpcal1,Mlip,...,Odf2l,Maged1,Mafb,Maf,Rab3b,Plch1,Wls,Dapk1,Ppm1k,Ankrd36
PS0817_E1-50_S19,0,0,0,12,0,0,1,2,0,0,...,0,728,417,0,537,0,0,0,0,0
PS0817_E1-50_S26,0,11,0,0,0,0,0,0,0,0,...,23,520,139,0,167,0,110,149,43,0
PS0817_E1-50_S27,0,0,0,267,31,0,3,0,0,0,...,0,665,6,17,99,0,0,38,0,0
PS0817_E1-50_S28,0,0,0,1005,1,0,1,1,0,0,...,0,110,58,0,530,0,25,56,0,0
PS0817_E1-50_S46,0,0,0,115,17,0,0,64,0,0,...,4,398,0,3,231,0,0,10,0,0

In [43]:
print(df_gene.shape)
print(df.shape)
df_gene.index.intersection(df.index)

(3654, 1302)
(3654, 41)

Index(['PS0817_E1-50_S19', 'PS0817_E1-50_S26', 'PS0817_E1-50_S27',
       'PS0817_E1-50_S28', 'PS0817_E1-50_S46', 'PS0817_E1-50_S52',
       'PS0830_E1-50_S17', 'PS0830_E1-50_S26', 'PS0830_E1-50_S70',
       'PS0830_E1-50_S83',
       ...
       'SM-J39TJ_S280_E1-50', 'SM-J39TJ_S281_E1-50', 'SM-J39TJ_S285_E1-50',
       'SM-J39TJ_S287_E1-50', 'SM-J39T2_S314_E1-50', 'SM-J39S6_S190_E1-50',
       'SM-J3A1L_S592_E1-50', 'SM-J3A1L_S593_E1-50', 'SM-J3A1L_S603_E1-50',
       'SM-J3A1L_S604_E1-50'],
      dtype='object', length=3654)

In [49]:
X_train, X_test = train_test_split(df.index, test_size=0.2)

Index(['PS0817_E1-50_S19', 'PS0817_E1-50_S26', 'PS0817_E1-50_S27',
       'PS0817_E1-50_S28', 'PS0817_E1-50_S46', 'PS0817_E1-50_S52',
       'PS0830_E1-50_S17', 'PS0830_E1-50_S26', 'PS0830_E1-50_S70',
       'PS0830_E1-50_S83',
       ...
       'SM-J39TJ_S280_E1-50', 'SM-J39TJ_S281_E1-50', 'SM-J39TJ_S285_E1-50',
       'SM-J39TJ_S287_E1-50', 'SM-J39T2_S314_E1-50', 'SM-J39S6_S190_E1-50',
       'SM-J3A1L_S592_E1-50', 'SM-J3A1L_S593_E1-50', 'SM-J3A1L_S603_E1-50',
       'SM-J3A1L_S604_E1-50'],
      dtype='object', name='Unnamed: 0', length=3654)

In [51]:
X_train

Index(['SM-GE8YI_S090_E1-50', 'SM-GE93V_S056_E1-50', 'SM-GE95A_S012_E1-50',
       'SM-GE92Y_S031_E1-50', 'SM-GE94J_S087_E1-50', 'SM-GE67S_S140_E1-50',
       'SM-GE4QF_S089_E1-50', 'SM-GE652_S136_E1-50', 'SM-GE95A_S019_E1-50',
       'SM-GE4Y5_S128_E1-50',
       ...
       'SM-GE5VE_S021_E1-50', 'SM-GE5QE_S039_E1-50', 'SM-GE67S_S141_E1-50',
       'SM-GE5UX_S138_E1-50', 'SM-GE8ZP_S182_E1-50', 'SM-GE5TI_S191_E1-50',
       'SM-GE8XZ_S118_E1-50', 'SM-GE65Z_S067_E1-50', 'SM-GE5TM_S173_E1-50',
       'SM-GE4RS_S057_E1-50'],
      dtype='object', name='Unnamed: 0', length=2923)